[project]
name = "word-of-the-day"
version = "0.1.3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "beautifulsoup4",
  "pytelegrambotapi",
  "python-dotenv",
  "schedule",
  "moviepy",
  "pymongo",
  "google-generativeai",
]
